### ISSUE TITLE
[bug] moon crashing with "Failed to load and create WASM plugin"

### ISSUE THREAD

**Issue by philippeauriach** [moonrepo/moon#1139] opened 2023-10-23 10:26 UTC
**Describe the bug**

On both our js monorepos (one with pnpm, the other with yarn) managed by moon, we are suddenly getting a lot of errors. It works fine in local, as long as we don't remove our local cache of prototools plugin.

The errors we get : 

```
[ERROR 2023-10-23 09:56:02] log:run  Encountered a critical error, aborting the action pipeline  log.target="moon:action-pipeline:batch:1" log.module_path="moon_action_pipeline::pipeline" log.file="crates/core/action-pipeline/src/pipeline.rs" log.line=216
Error: plugin::create::failed

  × Failed to load and create WASM plugin: ��,mU x$j��+�,mU��^j�3
  ╰─▶ ��,mU x$j��+�,mU��^j�3
```

```
[ERROR 2023-10-23 09:55:56] log:run  Encountered a critical error, aborting the action pipeline  log.target="moon:action-pipeline:batch:1" log.module_path="moon_action_pipeline::pipeline" log.file="crates/core/action-pipeline/src/pipeline.rs" log.line=216
Error: plugin::create::failed

  × Failed to load and create WASM plugin: @Q�Dimport: `env::get_env_var` has
  │ not been defined
  ╰─▶ @Q�Dimport: `env::get_env_var` has not been defined
```

```
Error: plugin::create::failed

Error:   × Main thread panicked.
  ├─▶ at /root/.cargo/registry/src/index.crates.io-6f17d[22](https://github.com/mobsuccess-devops/mobsuccess-front/actions/runs/6574367582/job/17955888941?pr=539#step:7:23)bba15001f/textwrap-
  │   0.15.2/src/word_separators.rs:258:40
thread panicked while processing panic. aborting.
```

**Steps to reproduce**

1. Remove all plugins under $HOME/.proto.plugins
2. Launch a command such as `moon run :eslint`
3. See the crash

**Expected behavior**
3. Dont crash

**Environment**

This is my local env, but we have the same issues on github action hosted runner
<details>
<summary>Toggle env</summary>
```
  System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M1 Max
    Memory: 2.47 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.6.0 - ~/.asdf/installs/nodejs/20.6.0/bin/node
    npm: 9.8.1 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 8.7.3 - ~/.asdf/installs/nodejs/20.6.0/.npm/bin/pnpm
    Watchman: 2023.07.10.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.13.0 - $HOME/.asdf/shims/pod
    Homebrew: 4.1.14 - /opt/homebrew/bin/brew
    pip3: 22.0.4 - ~/.asdf/shims/pip3
    RubyGems: 3.3.7 - $HOME/.asdf/shims/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 15.0.0 - /usr/bin/gcc
    Git: 2.39.3 - /usr/bin/git
    Clang: 15.0.0 - /usr/bin/clang
    Curl: 8.1.2 - /usr/bin/curl
  Servers:
    Apache: 2.4.56 - /usr/sbin/apachectl
  Virtualization:
    Docker: 24.0.2 - /usr/local/bin/docker
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    Android SDK:
      API Levels: 26, 28, 29, 30, 31, 32, 33
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0
      System Images: android-28 | Google APIs ARM 64 v8a, android-29 | Google Play ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-31 | Google Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    VSCode: 1.83.1 - /usr/local/bin/code
    Vim: 9.0 - /usr/bin/vim
    Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Go: 1.21.1 - $HOME/.asdf/shims/go
    Java: 11.0.11 - /usr/bin/javac
    Perl: 5.30.3 - /usr/bin/perl
    Python: 3.8.13 - $HOME/.asdf/shims/python
    Python3: 3.8.13 - $HOME/.asdf/shims/python3
    Ruby: 3.1.2 - $HOME/.asdf/shims/ruby
  Databases:
    PostgreSQL: 14.9 - /Applications/Postgres.app/Contents/Versions/14/bin/postgres
    SQLite: 3.39.5 - /usr/bin/sqlite3
  Browsers:
    Chrome: 118.0.5993.88
    Safari: 17.0
```
</details>

**Additional context**

The job ran ok before the weekend, and now it crashes on ALL our pull requests. We suspect an issue with the updated version of the proto plugins, and are currently trying to find a way to "fix" them to their previous version

[EDIT]

We used moon 1.13.4, and while we were planning to update, we did not yet. By updating moon to the latest version, it seems to work. Is there any way the plugins could be fixed in version so that they could not be upgraded and break previous versions of moon ?

**Comment by milesj** [comment] 2023-10-23 16:33
We posted this in the Discord, but you can do this for now:

If you're on an older version of moon (>=1.13), and your running into errors with Node.js like:

> Failed to load and create WASM plugin: V import: `env::get_env_var` has not been defined

You can solve this by pinning an older version of the Node.js plugins in your toolchain.

```yaml
node:
    version: '20.0.0'
    plugin: 'https://github.com/moonrepo/node-plugin/releases/download/v0.3.2/node_plugin.wasm'
    npm: # pnpm, yarn
        version: '9.0.0'
        plugin: 'https://github.com/moonrepo/node-plugin/releases/download/v0.3.2/node_depman_plugin.wasm'
```

The root cause is that we released a new version of the Node.js plugin that uses functionality released in proto v0.20, but older versions of moon are locked to older proto versions. We'll be looking into a way to mitigate this in the future.

**Comment by philippeauriach** [comment] 2023-10-23 18:03
Thanks ! We ended up upgrading to moon 1.15.3 and it fixed our issue. I will keep in mind that there might be more info on the discord for next time!

**Comment by milesj** [comment] 2023-10-23 18:16
No worries.

I'm going to keep this open for a bit as I'm sure others are hitting the problem.

**Comment by milesj** [comment] 2023-11-09 21:40
Been 2 weeks now, going to close.

**Closed by milesj** 2023-11-09 21:40 UTC
Labels: bug
