### ISSUE TITLE
[bug] Missing .env file breaks moon query project

### ISSUE THREAD

**Issue by tanepiper** [moonrepo/moon#273] opened 2022-08-16 15:35 UTC
**Describe the bug**

When running `moon query project` if a task in a project has `envFile` true but there is no `.env` (e.g. in a CI) it causes the whole command to fail.

**Steps to reproduce**

1. Set a task options to `envFile: true`
2. Run `moon query project`

**Expected behaviour**

The query should not fail, instead maybe a warning? 

**Screenshots**
No screenshot, but output:

```
Error: Command failed: yarn moon query projects
 ERROR 
Failed to parse env file ~/github/hub/services/api-auth/.env: No such file or directory (os error 2)
```

**Additional context**

The reason this is coming about is we have a CI task where you can pass the name of the task you want to run, internally a few scripts then I can get the workspace object:

```
export async function getWorkspace(workspace: string) {
  const buffer = await getExec('yarn moon query projects');
  const projectList = JSON.parse(buffer.stdout) as Record<string, any>;
  return projectList.projects.find((p: Record<string, any>) => p.id === workspace);
}
```

From this I can then get the root of the project - maybe this isn't a bug but a different command.

**Comment by milesj** [comment] 2022-08-16 16:51
@tanepiper This is even after the v0.11.1 patch? This is odd, since they all go through the same code path. Can you verify that the `CI` env var is set?

As you can see here, the `query projects` has nothing to do with `envFile`: https://github.com/moonrepo/moon/blob/master/crates/cli/src/queries/projects.rs

**Comment by milesj** [comment] 2022-08-23 07:05
Trying to reproduce this with no luck: https://github.com/moonrepo/moon/pull/281

**Comment by milesj** [comment] 2022-09-13 23:12
Gonna close this since I've been unable to reproduce.

**Closed by milesj** 2022-09-13 23:12 UTC
Labels: bug
