### ISSUE TITLE
[bug] WSL2 Ubuntu 22.04.1 fresh install tokio-runtime-worker panicked

### ISSUE THREAD

**Issue by NikolaRHristov** [moonrepo/moon#261] opened 2022-08-13 03:55 UTC
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: InvalidData, message: "stream did not contain valid UTF-8" }', crates/lang-node/src/node.rs:46:50
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by milesj** [comment] 2022-08-13 04:08
@NikolaRHristov What command did you run? You should be able to figure out the npm binary from that, and if so, can you paste the contents of the `node_modules/.bin` file?

**Comment by NikolaRHristov** [comment] 2022-08-13 14:16
Just ``moon run :build``. This is an archive of the node_modules folder.
[node_modules.zip](https://github.com/moonrepo/moon/files/9331563/node_modules.zip)

**Comment by milesj** [comment] 2022-08-13 18:18
@NikolaRHristov What's the build task configured as? Can you paste the yaml?

**Comment by NikolaRHristov** [comment] 2022-08-13 18:48
Yeah, you can see the repo live here - https://github.com/NikolaRHristov/test

**Comment by milesj** [comment] 2022-08-13 19:28
Ok I believe the problem is that build is running `esbuild`, and since esbuild is an executable (go lang), moon crashes when trying to read it. I should be able to work around this.

**Comment by milesj** [comment] 2022-08-14 06:06
This is fixed in v0.11.

**Closed by milesj** 2022-08-14 06:06 UTC
Labels: bug
