### ISSUE TITLE
windows - global moon install is not working in powershell (flashes new shell window)

### ISSUE THREAD

**Issue by alexn-s** [moonrepo/moon#176] opened 2022-07-01 23:06 UTC
**Describe the bug**

running moon just flashes a shell windows which closes directly (probably opens/ runs in new shell and closes immediately after). i recorded the issue with a screen recorder, but the flashing cmd window does not show

**Steps to reproduce**

install under windows with `npm install -g @moonrepo/cli`

**Screenshots**
![WindowsTerminal_mVpShsS6cf](https://user-images.githubusercontent.com/60710873/176976355-e356a1cf-0fa0-48ee-8741-e1baea02895e.gif)

**Environment**

os: `windows 11`
shell: `PowerShell 7.2.5`
moon path: `C:\Users\...\AppData\Roaming\npm\moon.CMD`

```
 System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 AMD Ryzen 5 4600H with Radeon Graphics
    Memory: 3.81 GB / 15.37 GB
  Binaries:
    Node: 16.3.0 - C:\Program Files\nodejs\node.EXE
    npm: 7.15.1 - C:\Program Files\nodejs\npm.CMD
  Managers:
    Cargo: 1.61.0 - ~\.cargo\bin\cargo.EXE
    pip3: 19.2.3 - ~\AppData\Local\Programs\Python\Python37-32\Scripts\pip3.EXE
    RubyGems: 3.2.32 - C:\Program Files\Ruby30-x64\bin\gem.CMD
  Utilities:
    Git: 2.32.0.
  Virtualization:
    Docker: 20.10.14 - C:\Program Files\Docker\Docker\resources\bin\docker.EXE
  SDKs:
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    VSCode: 1.68.1 - C:\Users\aschu\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
    Visual Studio: 16.10.31424.327 (Visual Studio Community 2019)
  Languages:
    Bash: 5.0.17 - C:\WINDOWS\system32\bash.EXE
    Go: 1.16.6 - C:\Program Files\Go\bin\go.EXE
    Java: 18.0.1.1
    Perl: 5.32.1 - C:\Pearl\perl\bin\perl.EXE
    Python: 3.7.7
    Ruby: 3.0.3 - C:\Program Files\Ruby30-x64\bin\ruby.EXE
    Rust: 1.61.0
  Databases:
    PostgreSQL: 14.1 - C:\Program Files\PostgreSQL\14\bin\postgres.EXE
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (103.0.1264.44), ChromiumDev (None)
    Internet Explorer: 11.0.22000.120
```

**Additional context**

running moon within package.json (`npm run moon ...`) works and install moon in ubuntu via wsl under windows works as well.

**Comment by alexn-s** [comment] 2022-07-02 05:03
apparently moon cli works in cmd.exe prompt, just not in powershell.

as a workaround in powershell moon can be used via the following commands in powershell:
`cmd /c moon ...` (execs the command in cmd.exe)

**Comment by milesj** [comment] 2022-07-04 01:23
moon currently works by executing the `.cmd` files in `node_modules/.bin` through cmd.exe, which I'm assuming is causing this.

I have a feeling I'll need to resolve the `.js` file to execute, by resolving node modules manually. This means I'll have to implement this logic in Rust, which is unfortunate... but fun?

**Comment by milesj** [comment] 2022-07-04 02:20
Looking into this here: https://github.com/moonrepo/moon/pull/177

**Comment by milesj** [comment] 2022-07-04 05:34
I've been testing things, and when you `npm run <script>`, npm executes the `*.cmd` file using "C:\WINDOWS\system32\cmd.exe", which is exactly how I'm running it as well. Hrmm..

**Comment by milesj** [comment] 2022-07-04 18:15
I was able to resolve this locally. A fix will land with the next version.

**Comment by milesj** [comment] 2022-07-13 19:46
Going to close this as I cannot reproduce anymore.

**Closed by milesj** 2022-07-13 19:46 UTC
Labels: bug

**Comment by alexn-s** [comment] 2022-07-25 15:21
@milesj  just checked it and everything works fine. thank you
