### ISSUE TITLE
[bug] Detect Node Instead of Installing

### ISSUE THREAD

**Issue by shellscape** [moonrepo/moon#693] opened 2023-03-13 16:50 UTC
**Describe the bug**

When first running a command, we see "installing Node <version>" in the console. Moon should detect if node is installed and skip that step, or there should be a setting to disable installing node.

We manage our node versions with NVM and that's already been installed on the system. We don't mandate that our devs have to use NVM and can use a global install from another source, or build from source if they choose. Moon shouldn't assert a node install in this scenario.

This same idea applies to the installation of PNPM.

**Steps to reproduce**

Init a fresh Node+Moon repo

**Expected behavior**

No superfluous node installs.

**Screenshots**

**Environment**

MacOS Ventura

**Additional context**

**Comment by milesj** [comment] 2023-03-13 17:11
@shellscape Sorry to say, but one workflow that moon is trying to solve is version differences across machines, both for developers and CI/CD. After years of supporting developers, relying on purely on nvm simply doesn't work (it's why we built proto https://moonrepo.dev/proto), so moon automates this and manages the toolchain behind the scenes. I'll actually say this is the biggest selling point to using moon, especially if you come from something like Bazel.

However! If you're so inclined, you can avoid the toolchain by not setting the `version` fields in `toolchain.yml`. This will fallback to the node available on the machine. https://moonrepo.dev/docs/guides/javascript/node-handbook#utilizing-the-toolchain

**Comment by shellscape** [comment] 2023-03-13 17:45
I see, and understood. I'd like to suggest that the docs could be improved to include the inverse to this:

```
Enabling the toolchain is as simple as defining the [node.version](https://moonrepo.dev/docs/config/toolchain#version) setting.
```

It wasn't clear that omitting the version would skip this node install portion of the toolchain. I understand that is def not what you all are going for, but it's helpful to understand that feature further.

**Comment by milesj** [comment] 2023-03-13 18:14
The paragraph above that sentences talks about using the system binary. Should I reword it?

**Comment by shellscape** [comment] 2023-03-13 18:25
Perhaps. For what it's worth, I went through the "Getting Started" guide first and landed on this section https://moonrepo.dev/docs/setup-toolchain#configuring-nodejs. When I ran into the errors mentioned in the OP, I went to the "Utilizing the Toolchain" page via search. Between the two sections is where I think I was confused. It could just be PEBCAK on my part :D

**Comment by milesj** [comment] 2023-03-13 18:37
Ah yeah that's fair, forgot about that page. I need to rewrite those docs, they're pretty old at this point.

**Comment by milesj** [comment] 2023-03-14 22:04
Gonna close this since it's working as intended.

I did update the docs though: https://github.com/moonrepo/moon/pull/704

**Closed by milesj** 2023-03-14 22:04 UTC
Labels: bug
