### ISSUE TITLE
[bug] Can't use pnpm inside node:alpine when using moon docker setup

### ISSUE THREAD

**Issue by theomessin** [moonrepo/moon#1203] opened 2023-11-24 03:23 UTC
**Describe the bug**

Using pnpm inside docker `node:alpine` image breaks when running ` moon docker setup`. We get the following error:

```
 => ERROR [setup 3/3] RUN moon docker setup                                                                                                                                                          6.3s
------                                                                                                                                                                                                    
 > [setup 3/3] RUN moon docker setup:                                                                                                                                                                     
1.752 ▪▪▪▪ installing node 20.0.0                                                                                                                                                                         
5.631 ▪▪▪▪ installing pnpm 8.10.5                                                                                                                                                                         
6.147 ▪▪▪▪ pnpm install
6.147 /root/.proto/tools/node/20.0.0/bin/node /root/.proto/tools/pnpm/8.10.5/bin/pnpm.cjs install (in workspace)
6.153 [ERROR 2023-11-24 03:09:09] log:setup  Encountered a critical error, aborting the action pipeline  log.target="moon_action_pipeline::pipeline" log.module_path="moon_action_pipeline::pipeline" log.file="crates/core/action-pipeline/src/pipeline.rs" log.line=343
6.154 Error: process::stream::failed
6.154 
6.154   × Failed to execute ~/.proto/tools/node/20.0.0/bin/node and stream output.
6.154   ╰─▶ No such file or directory (os error 2)
6.154 
------
Dockerfile:17
--------------------
  15 |     WORKDIR /app
  16 |     COPY --from=workspace /app/.moon/docker/workspace .
  17 | >>> RUN moon docker setup
  18 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c moon docker setup" did not complete successfully: exit code: 1
```

**Steps to reproduce**

See reproduction repo: https://github.com/theomessin/moon-docker-alpine-issue

**Expected behavior**

It should work

**Comment by milesj** [comment] 2023-11-24 06:00
@theomessin Can you run it with `--log trace`? Maybe it will uncover which file is missing.

**Comment by theomessin** [comment] 2023-11-24 06:41
Sure! Here you go 😄 
[trace.log](https://github.com/moonrepo/moon/files/13455805/trace.log)

**Comment by milesj** [comment] 2023-11-24 08:32
Hrmm still hard to tell. Kind of seems like `/root/.proto/tools/pnpm/8.10.5/bin/pnpm.cjs` is missing? Or a file that pnpm required is missing.

The package.json/lockfiles are in the image yeah? I believe it is from the workspace copy, just want to confirm.

If you manually run pnpm in `.moon/docker/workspace`, does it work correctly?

**Comment by theomessin** [comment] 2023-11-24 08:57
Yeah everything's there:
```sh
#13 [setup 3/3] RUN find . && moon docker setup
#13 0.238 .
#13 0.238 ./packages
#13 0.238 ./packages/app
#13 0.238 ./packages/app/package.json
#13 0.238 ./packages/lib
#13 0.238 ./packages/lib/package.json
#13 0.238 ./pnpm-workspace.yaml
#13 0.238 ./dockerManifest.json
#13 0.238 ./pnpm-lock.yaml
#13 0.238 ./.moon
#13 0.238 ./.moon/toolchain.yml
#13 0.238 ./.moon/workspace.yml
#13 1.763 ▪▪▪▪ installing node 20.0.0
#13 5.691 ▪▪▪▪ installing pnpm 8.10.5
#13 6.214 ▪▪▪▪ pnpm install
#13 6.214 /root/.proto/tools/node/20.0.0/bin/node /root/.proto/tools/pnpm/8.10.5/bin/pnpm.cjs install (in workspace)
#13 6.220 [ERROR 2023-11-24 08:56:24] log:setup  Encountered a critical error, aborting the action pipeline  log.target="moon_action_pipeline::pipeline" log.module_path="moon_action_pipeline::pipeline" log.file="crates/core/action-pipeline/src/pipeline.rs" log.line=343
#13 6.221 Error: process::stream::failed
#13 6.221 
#13 6.221   × Failed to execute ~/.proto/tools/node/20.0.0/bin/node and stream output.
#13 6.221   ╰─▶ No such file or directory (os error 2)
#13 6.221 
#13 ERROR: process "/bin/sh -c find . && moon docker setup" did not complete successfully: exit code: 1
------sh
 > [setup 3/3] RUN find . && moon docker setup:
1.763 ▪▪▪▪ installing node 20.0.0
5.691 ▪▪▪▪ installing pnpm 8.10.5
6.214 ▪▪▪▪ pnpm install
6.214 /root/.proto/tools/node/20.0.0/bin/node /root/.proto/tools/pnpm/8.10.5/bin/pnpm.cjs install (in workspace)
6.220 [ERROR 2023-11-24 08:56:24] log:setup  Encountered a critical error, aborting the action pipeline  log.target="moon_action_pipeline::pipeline" log.module_path="moon_action_pipeline::pipeline" log.file="crates/core/action-pipeline/src/pipeline.rs" log.line=343
6.221 Error: process::stream::failed
6.221 
6.221   × Failed to execute ~/.proto/tools/node/20.0.0/bin/node and stream output.
6.221   ╰─▶ No such file or directory (os error 2)
6.221 
------
Dockerfile:17
--------------------
  15 |     WORKDIR /app
  16 |     COPY --from=workspace /app/.moon/docker/workspace .
  17 | >>> RUN find . && moon docker setup
  18 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c find . && moon docker setup" did not complete successfully: exit code: 1
...
```

Even the file that is "missing" is actually there 🤷🏼 
```
~/.proto/tools/node/20.0.0/bin # ls -al
total 93344
drwxr-xr-x    2 root     root          4096 Nov 24 08:53 .
drwxr-xr-x    6 root     root          4096 Nov 24 08:53 ..
lrwxrwxrwx    1 root     root            45 Apr 17  2023 corepack -> ../lib/node_modules/corepack/dist/corepack.js
-rwxr-xr-x    1 root     root      95571056 Apr 17  2023 node
lrwxrwxrwx    1 root     root            38 Apr 17  2023 npm -> ../lib/node_modules/npm/bin/npm-cli.js
lrwxrwxrwx    1 root     root            38 Apr 17  2023 npx -> ../lib/node_modules/npm/bin/npx-cli.js
```

**Comment by theomessin** [comment] 2023-11-24 09:01
Yeah, everything is there:

```sh
#13 [setup 3/3] RUN find . && moon docker setup
#13 0.238 .
#13 0.238 ./packages
#13 0.238 ./packages/app
#13 0.238 ./packages/app/package.json
#13 0.238 ./packages/lib
#13 0.238 ./packages/lib/package.json
#13 0.238 ./pnpm-workspace.yaml
#13 0.238 ./dockerManifest.json
#13 0.238 ./pnpm-lock.yaml
#13 0.238 ./.moon
#13 0.238 ./.moon/toolchain.yml
#13 0.238 ./.moon/workspace.yml
#13 1.763 ▪▪▪▪ installing node 20.0.0
#13 5.691 ▪▪▪▪ installing pnpm 8.10.5
#13 6.214 ▪▪▪▪ pnpm install
#13 6.214 /root/.proto/tools/node/20.0.0/bin/node /root/.proto/tools/pnpm/8.10.5/bin/pnpm.cjs install (in workspace)
#13 6.220 [ERROR 2023-11-24 08:56:24] log:setup  Encountered a critical error, aborting the action pipeline  log.target="moon_action_pipeline::pipeline" log.module_path="moon_action_pipeline::pipeline" log.file="crates/core/action-pipeline/src/pipeline.rs" log.line=343
#13 6.221 Error: process::stream::failed
#13 6.221 
#13 6.221   × Failed to execute ~/.proto/tools/node/20.0.0/bin/node and stream output.
#13 6.221   ╰─▶ No such file or directory (os error 2)
#13 6.221 
#13 ERROR: process "/bin/sh -c find . && moon docker setup" did not complete successfully: exit code: 1
------
 > [setup 3/3] RUN find . && moon docker setup:
1.763 ▪▪▪▪ installing node 20.0.0
5.691 ▪▪▪▪ installing pnpm 8.10.5
6.214 ▪▪▪▪ pnpm install
6.214 /root/.proto/tools/node/20.0.0/bin/node /root/.proto/tools/pnpm/8.10.5/bin/pnpm.cjs install (in workspace)
6.220 [ERROR 2023-11-24 08:56:24] log:setup  Encountered a critical error, aborting the action pipeline  log.target="moon_action_pipeline::pipeline" log.module_path="moon_action_pipeline::pipeline" log.file="crates/core/action-pipeline/src/pipeline.rs" log.line=343
6.221 Error: process::stream::failed
6.221 
6.221   × Failed to execute ~/.proto/tools/node/20.0.0/bin/node and stream output.
6.221   ╰─▶ No such file or directory (os error 2)
6.221 
------
Dockerfile:17
--------------------
  15 |     WORKDIR /app
  16 |     COPY --from=workspace /app/.moon/docker/workspace .
  17 | >>> RUN find . && moon docker setup
  18 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c find . && moon docker setup" did not complete successfully: exit code: 1
```

Yeah manually running `pnpm install` works.

Weirdly, the file it's complaining about is there:

```sh
~/.proto/tools/node/20.0.0/bin # ls -al
total 93344
drwxr-xr-x    2 root     root          4096 Nov 24 08:53 .
drwxr-xr-x    6 root     root          4096 Nov 24 08:53 ..
lrwxrwxrwx    1 root     root            45 Apr 17  2023 corepack -> ../lib/node_modules/corepack/dist/corepack.js
-rwxr-xr-x    1 root     root      95571056 Apr 17  2023 node
lrwxrwxrwx    1 root     root            38 Apr 17  2023 npm -> ../lib/node_modules/npm/bin/npm-cli.js
lrwxrwxrwx    1 root     root            38 Apr 17  2023 npx -> ../lib/node_modules/npm/bin/npx-cli.js
```

**Comment by milesj** [comment] 2023-11-24 19:33
In that `find .`, it looks like the root `package.json` is missing. Would that be the problem?

**Comment by theomessin** [comment] 2023-11-24 21:01
We don't use a root package.json, we also don't have a root `pnpm-lock.yaml` (we use `shared-workspace-lockfile=false`).
Works fine with just `node` image (ubuntu).

**Comment by milesj** [comment] 2023-11-25 05:35
This is definitely weird. If you could create a repo with a very basic example that I can reproduce, that would be helpful.

**Comment by theomessin** [comment] 2023-11-26 00:49
I already have, see steps to reproduce.

**Comment by milesj** [comment] 2023-11-26 19:50
Sorry, long holiday weekend!

**Comment by milesj** [comment] 2023-11-26 20:36
This is very weird. The node files exist in the image:

```
~/.proto/tools/node/20.0.0/bin # ls
corepack  node      npm       npx
```

But it still says not found. I wonder if it's an arch mismatch or something.

```
/app # ~/.proto/tools/node/20.0.0/bin/node --version
sh: /root/.proto/tools/node/20.0.0/bin/node: not found
```

**Comment by milesj** [comment] 2023-11-26 20:50
So I think the problem is that Node.js downloads by default do not support musl/alpine: https://nodejs.org/download/release/v20.0.0/ And this is what moon downloads and uses.

I think your best option here is to set `MOON_TOOLCHAIN_FORCE_GLOBALS=1`.

This will use the node/pnpm found on `PATH` instead of attempting to download them.

**Comment by theomessin** [comment] 2023-11-26 22:29
Gotcha. Okay that's useful to know, thanks! Feel free to keep or close the issue 😄

**Comment by milesj** [comment] 2023-12-10 21:47
Going to close this but will update the docs about this scenario.

**Closed by milesj** 2023-12-10 21:47 UTC
Labels: bug
