### ISSUE TITLE
[bug]  problem with the moon binary

### ISSUE THREAD

**Issue by Guchii** [moonrepo/moon#504] opened 2022-12-16 14:21 UTC
**Describe the bug**

`moon --log debug setup` didn't work for me. Some kind of issue with the moon binary.  

**Expected behavior**

should tell if node is setup properly or not, I believe.

**Screenshots**

![image](https://user-images.githubusercontent.com/71770229/208117873-30474239-d72a-42c4-9b76-0e618d7b3b50.png)

**Environment**

```
 System:
    OS: Linux 5.15 Manjaro Linux
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 2.74 GB / 7.64 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Managers:
    Cargo: 1.63.0 - /usr/bin/cargo
    Composer: 2.4.1 - /usr/bin/composer
    pip3: 22.2.2 - /usr/bin/pip3
  Utilities:
    CMake: 3.24.1 - /usr/bin/cmake
    Make: 4.3 - /usr/bin/make
    GCC: 12.2.0 - /usr/bin/gcc
    Git: 2.37.3 - /usr/bin/git
    Clang: 14.0.6 - /usr/bin/clang
    Ninja: 1.11.1 - /usr/bin/ninja
    FFmpeg: 5.1.1 - /usr/bin/ffmpeg
  Servers:
    Apache: 2.4.54 - /usr/bin/apachectl
  Virtualization:
    Docker: 20.10.17 - /usr/bin/docker
  IDEs:
    Nano: 6.4 - /usr/bin/nano
    VSCode: 1.74.1 - /usr/bin/code
  Languages:
    Bash: 5.1.16 - /usr/bin/bash
    Go: 1.19 - /usr/bin/go
    Java: 1.8.0_345 - /usr/bin/javac
    Perl: 5.36.0 - /usr/bin/perl
    PHP: 8.1.10 - /usr/bin/php
    Protoc: 3.21.5 - /usr/bin/protoc
    Python: 3.10.6 - /usr/bin/python
    Python3: 3.10.6 - /usr/bin/python3
    Rust: 1.63.0 - /usr/bin/rustc
  Databases:
    PostgreSQL: 14.5 - /usr/bin/postgres
    SQLite: 3.39.3 - /usr/bin/sqlite3
  Browsers:
    Brave Browser: 103.1.40.105
    Firefox: 105.0.2
```

**Additional context**

**Comment by Guchii** [comment] 2022-12-16 14:29
In fact no command is working for me, same output. I tried `moon run docs:typecheck --affected`

**Comment by milesj** [comment] 2022-12-16 18:08
@Guchii It's failing on this line, which can mean a few things: https://github.com/moonrepo/moon/blob/master/crates/cli/src/main.rs#L107

I'm assuming you're running moon via global install, probably through npm? Can you try executing the binary manually found at `node_modules/@moonrepo/cli/moon`?

**Comment by IgnisDa** [comment] 2022-12-17 00:37
He has it installed globally, but he is also using `nvm`. Maybe that is introducing some problems?

**Comment by milesj** [comment] 2022-12-19 21:04
@Guchii Was this installed via pnpm? I think I reproduced it there.

**Comment by milesj** [comment] 2022-12-20 05:35
@Guchii Did you update to latest version by chance?

**Comment by IgnisDa** [comment] 2022-12-20 12:00
Would be pretty convenient if the trace logs display the version.

**Comment by milesj** [comment] 2022-12-23 19:53
Good idea, added here: https://github.com/moonrepo/moon/pull/514

I'll also close this since it's resolved.

**Closed by milesj** 2022-12-23 19:53 UTC
Labels: bug
