### ISSUE TITLE
[feature] Ability to query for tasks that are affected by changed files.

### ISSUE THREAD

**Issue by indietyp** [moonrepo/moon#1032] opened 2023-09-03 13:12 UTC
**Is your feature request related to a problem? Please describe.**

I am currently looking for a replacement for `turborepo run --dry-run` which will tell one which tasks are to be executed with the changed files. I know that `moon ci` and `moon query tasks` exists. I thought that if I would do `moon query tasks --affected` I would get a list of tasks that will trigger with the affected files, but that doesn't seem to be the case, as filtering for affected files will only change so that tasks of projects that have been affected are display.

**Describe the solution you'd like**

A command to essentially get the same output of `moon ci` (maybe a `--dry-run` option or `moon query` command) that enables on to query which tasks are to be executed based on the affected files.

**Describe alternatives you've considered**

Try to implement this myself using a chain of commands, but because of globs that may not be as straight-forward.

**Comment by milesj** [comment] 2023-09-03 19:44
@indietyp I haven't tried this yet but I think you can do this:

```
moon query touched-files | moon query tasks --affected
```

**Comment by indietyp** [comment] 2023-09-03 19:45
I tried exactly that, but that will only give me all tasks of projects that have affected files.

**Comment by milesj** [comment] 2023-09-03 20:03
I can patch it to also apply affected at the task level.

**Comment by milesj** [comment] 2023-09-04 21:02
@indietyp Can you try 1.13?

**Comment by shellscape** [comment] 2023-09-12 01:55
@milesj (I think this might be tangentially related) I came to the repo tonight to report that `moon run :deploy --affected` was not running any tasks in workflows. Do we need to pipe in touched files like outlined in https://github.com/moonrepo/moon/issues/1032#issuecomment-1704386081?

fwiw the latest commit is always squash merged. here's how we're checking out the branch in the workflow:

```yml
      - name: Checkout Branch
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 10
```

**Comment by milesj** [comment] 2023-09-12 16:39
@shellscape You need to use the `--remote` flag when running in CI. `moon run` was designed for local development, but people started using it in CI, so it's kind of a mix of things.

**Comment by indietyp** [comment] 2023-09-25 07:48
Sorry for the delay! It seems like it is now partially doing what I'd expected.

What I mean is the following: `moon query tasks --affected`

I have the projects `A` and `B`; `B` depends on `A`. I change a file in `A`; I'd expect that I now also need to rerun `build` in `B` (or let it at least show up), but only the tasks in `A` will show up (although not properly filtered) because `--affected` still filters on the project level and after that on the task level.

See:

https://github.com/moonrepo/moon/blob/fc821661d039b4ed99c87e2791384cb54b431f11/crates/cli/src/commands/query.rs#L233

https://github.com/moonrepo/moon/blob/fc821661d039b4ed99c87e2791384cb54b431f11/crates/cli/src/queries/projects.rs#L117

**Comment by milesj** [comment] 2023-09-25 16:54
@indietyp So transitive deps of tasks won't show up in the affected list, as `--affected` is simply the list of what has literally been affected based on files changed.

However, the task runner will appropriately run upstream and downstream dependencies of affected tasks. This is automatic with `moon ci` but you'll need to use `moon run --dependents`.

This logic happens in the task runner, because it requires the dependency graph, which the affected flow does not have access to.

**Comment by indietyp** [comment] 2023-09-25 16:56
A thanks! Then this solves my problem.

Maybe a note in the docs would help?

**Comment by milesj** [comment] 2023-09-25 17:41
Yeah I'll update the docs.

**Comment by milesj** [comment] 2023-09-28 23:06
Updated the docs.

**Closed by milesj** 2023-09-28 23:06 UTC
Labels: enhancement
