### ISSUE TITLE
This either means the dependency hasn't ran, has failed, or there's a misconfiguration [bug] 

### ISSUE THREAD

**Issue by elmpp** [moonrepo/moon#859] opened 2023-05-19 09:31 UTC
**Describe the bug**

moon task fails when dependency added from other package

**Steps to reproduce**

Failing trace: https://pastebin.com/5RJV2JLR
projectGraph.json: https://pastebin.com/ptiKANdp
root workspace config (./moon.yml): https://pastebin.com/fHFjMd2C
subworkspace config: (/packages/pkg-tests-verdaccio): https://pastebin.com/rc9Sifx9
main tasks (./.moon/tasks/typescript.yml): https://pastebin.com/wNsyxD8M

There seems to be a possible mismatch in the project names ¯\_(ツ)_/¯ (see screenshot of state folder names)

**Expected behavior**

Task should allow dep from other package

**Screenshots**

<img width="413" alt="Screenshot 2023-05-19 at 11 22 57" src="https://github.com/moonrepo/moon/assets/864612/fb573d7f-e566-4605-ac80-495c36a5eccc">

**Environment**

```
  System:
    OS: macOS 13.0.1
    CPU: (10) x64 Apple M1 Pro
    Memory: 17.84 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
```

**Additional context**

**Comment by elmpp** [comment] 2023-05-20 08:08
It seems if i move the tasks from `/packages/pkg-tests-verdaccio/moon.yml` up into `moon.yml` (i.e. same file), i do not get any errors. Maybe it's specific to root projects, else i'm misunderstanding moon's ability to take define deps from other projects

**Comment by milesj** [comment] 2023-05-22 16:54
@elmpp I believe the problem is, is that you can't depend on another task that is `local` if the parent task isn't `local` either.

`verdaccioEnsureRunning` is marked as local, but `changesetSnapshotPublishLocal` is not. I should make this an error honestly so that it's easier to catch.

You can try `options.cache = false` instead of local.

**Closed** 2023-05-22 18:02 UTC
Labels: bug
