### ISSUE TITLE
[bug] disable proto toolchain completely

### ISSUE THREAD

**Issue by dec0dOS** [moonrepo/moon#1214] opened 2023-12-04 18:59 UTC
**Describe the bug**

Currently, to disable Proto, it is necessary to pass the `MOON_TOOLCHAIN_FORCE_GLOBALS=true` to every moon command. This approach, while functional, may not be the most convenient for developers.

I propose the idea of introducing an option in the `toolchain.yml` file that allows for the complete disabling of moon's management of the toolchain. This addition could streamline the process and enhance usability for those who prefer an alternative setup.

Alternatively, could we consider a setup where removing the toolchain.yml file entirely would automatically disable Proto's management for Moon commands? This might offer a more intuitive way of handling the toolchain settings.

**Steps to reproduce**

1. Remove `toolchain.yml`
2. Run any moon task
3. `Error: project::task::unknown`

**Expected behavior**

Moon works perfectly fine with global tools declared in the PATH. 

**Additional context**

I wanted to share my thoughts regarding the potential adoption of Proto. While it's an interesting project, I have some reservations about its feasibility for widespread use in the future.

I've noticed that for certain unique environments, the Nix project has effectively addressed similar challenges. Additionally, tools like [devenv.sh](https://devenv.sh) and [Jetpack Devbox](https://www.jetpack.io/devbox) offer streamlined solutions for declaring complex environments. These tools accomplish this without requiring users to learn the more intricate aspects of the Nix DSL.

From my perspective, Nix appears to provide a more efficient solution for creating shareable environments compared to what Proto currently offers.

**Comment by milesj** [comment] 2023-12-04 19:40
@dec0dOS The toolchain already works this way. Either remove the `version` field from the `toolchain.yml` tools, which will use the binaries on `PATH`, or remove the config entirely (requires `system` platform).

**Comment by milesj** [comment] 2023-12-04 21:21
@dec0dOS Is there an error? Or does it just do nothing?

Maybe try wiping the cache.

**Comment by milesj** [comment] 2023-12-04 23:36
Let me see if I can reproduce something.

**Comment by milesj** [comment] 2023-12-05 00:55
Thanks for the reproduction, will look into.

> I've noticed an additional issue that occurs when the packageManager: "yarn" line is removed from the toolchain.yml file. In such cases, it appears that npm is being used instead, which seems unexpected

This is expected right now. The commands moon runs for package managers is dependent entirely on that setting. It defaults to npm since that's what comes with node.

In v2, once we migrate to wasm plugins, this will change.

**Comment by milesj** [comment] 2023-12-10 00:08
Been messing with your repro and I think the problem is is that moon removes the `packageManager` field, messing up the yarn/corepack version.

**Comment by milesj** [comment] 2023-12-12 05:51
this should be fixed in v1.18

**Closed by milesj** 2023-12-12 05:51 UTC
Labels: bug
